# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  Version.MajorMinor: 1.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)
  $VERSION: variables['Version.MajorMinor'].variables['Version.Revision']


steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.3'
- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'
- task: Bash@3
  displayName: 'Bash Script'
  inputs:
    targetType: filePath
    filePath: ./scripts/deploy.sh
