version: '3'
services:
    
    db:
        image: mongo:4.2.8
        container_name: db

        ports:
            - "4002:27017"
        restart: always

    web:
        image: web
        build: 
            context: ./web
            dockerfile: Dockerfile-dev
        container_name: web
        volumes:
            - /tmp/web/npm-cache:/root/.npm:z
            - ./web:/usr/src/app:z
        ports:
            - "4000:80"    
        environment:
            - PORT=80
            - FEED_HOST=feed-reader
            - FEED_PORT=80
            - NODE_ENV=development
            - DBHOST=mongodb://db:27017
            - DBNAME=myrunningcircle
        depends_on:
            - db
        restart: "no"

    feed-reader:
        image: feed-reader
        build: 
            context: ./feed-reader
            dockerfile: Dockerfile-dev
        container_name: feed-reader
        volumes:
            - /tmp/feed-reader/npm-cache:/root/.npm:z
            - ./feed-reader:/usr/src/app:z
        ports:
            - "4001:80"    
        environment:
            - PORT=80
            - DBHOST=mongodb://db:27017
            - DBNAME=myrunningcircle
            - STRAVA_CONNECTOR_HOST=strava-connector
            - STRAVA_CONNECTOR_PORT=80
            - NODE_ENV=development
        depends_on:
            - db
            - strava-connector
        restart: "no"
    
    strava-connector:
        image: strava-connector
        build:
            context: ./strava-connector
            dockerfile: Dockerfile-dev
        container_name: strava-connector
        volumes:
            - /tmp/strava-connector/npm-cache:/root/.npm:z
            - ./strava-connector:/usr/src/app:z
        ports:
            - "4003:80"    
        environment:
            - PORT=80
            - NODE_ENV=development
        restart: "no"
