version: '3'
services:

  web:
    image: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
     - "3001:80"
    environment:
      - PORT=80
    restart: "no"