version: '3'
services:
    
    db:
        image: mongo:4.2.8
        container_name: db

        ports:
            - "4002:27017"
        restart: always

    web:
        image: web
        build: 
            context: ./web
            dockerfile: Dockerfile
        container_name: web
        ports:
            - "4000:80"    
        environment:
            - PORT=80
            - FEED_HOST=feed-reader
            - FEED_PORT=4001
        restart: "no"

    feed-reader:
        image: feed-reader
        build: 
            context: ./feed-reader
            dockerfile: Dockerfile
        container_name: feed-reader
        ports:
            - "4001:80"    
        environment:
            - PORT=80
            - DBHOST=mongodb://db:27017
            - DBNAME=feeds
        depends_on:
            - db
        restart: "no"