FROM node:12.18.1-alpine

ARG FACEBOOK_APP_ID
ARG FACEBOOK_APP_SECRET

ENV FACEBOOK_APP_ID = $(FACEBOOK_APP_ID)
ENV FACEBOOK_APP_SECRET = $(FACEBOOK_APP_SECRET)
ENV APP_IP = $(APP_IP)

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY ./app.js ./
COPY ./passport.js ./
COPY ./configs ./configs
COPY ./controllers ./controllers
COPY ./routes ./routes
COPY ./views ./views
COPY ./middleware ./middleware
COPY ./public ./public
COPY ./utils ./utils
CMD npm start
