FROM node:12.18.1-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY ./app.js ./
COPY ./passport.js ./
COPY ./.env ./
COPY ./configs ./configs
COPY ./controllers ./controllers
COPY ./routes ./routes
COPY ./views ./views
COPY ./middleware ./middleware
COPY ./public ./public
COPY ./utils ./utils
CMD npm start
